### ISSUE TITLE
Tests failing on Linux

### ISSUE THREAD

**Issue by bnewbold** [datprotocol/integration-tests#1]
On my GNU/Linux box (Debian stretch, amd64), with mininet:

```
bnewbold@orithena$ mn --version
2.2.1
```

The tests don't succeed:

```
bnewbold@orithena$ npm test

> integration-tests@1.0.0 test /home/bnewbold/dat/integration-tests
> tapenet tests/**/*

TAP version 13
# share a dat between two nodes
ok 1 h2 sharing dat://99e40fca21249cf06baca9075022538929074ae7b347ed4427d0c563ccdff76d
ok 2 h1 downloading dat://99e40fca21249cf06baca9075022538929074ae7b347ed4427d0c563ccdff76d
not ok 3 h2 joinNetwork calls back okay
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      'Error: Query failed'
    at: EventEmitter.<anonymous> (/home/bnewbold/dat/integration-tests/node_modules/tapenet/index.js:134:20)
    stack: |-
      Error: h2 joinNetwork calls back okay
          at Test.assert [as _assert] (/home/bnewbold/dat/integration-tests/node_modules/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/home/bnewbold/dat/integration-tests/node_modules/tape/lib/test.js:77:32)
          at Test.error.Test.ifError.Test.ifErr.Test.iferror (/home/bnewbold/dat/integration-tests/node_modules/tape/lib/test.js:373:10)
          at Test.bound [as error] (/home/bnewbold/dat/integration-tests/node_modules/tape/lib/test.js:77:32)
          at EventEmitter.<anonymous> (/home/bnewbold/dat/integration-tests/node_modules/tapenet/index.js:134:20)
          at emitOne (events.js:96:13)
          at EventEmitter.emit (events.js:191:7)
          at DestroyableTransform.<anonymous> (/home/bnewbold/dat/integration-tests/node_modules/mininet/index.js:294:10)
          at emitOne (events.js:96:13)
          at DestroyableTransform.emit (events.js:191:7)
  ...
not ok 4 h1 joinNetwork calls back okay
  ---
    operator: error
    expected: |-
      undefined
    actual: |-
      'Error: Query failed'
    at: EventEmitter.<anonymous> (/home/bnewbold/dat/integration-tests/node_modules/tapenet/index.js:134:20)
    stack: |-
      Error: h1 joinNetwork calls back okay
          at Test.assert [as _assert] (/home/bnewbold/dat/integration-tests/node_modules/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/home/bnewbold/dat/integration-tests/node_modules/tape/lib/test.js:77:32)
          at Test.error.Test.ifError.Test.ifErr.Test.iferror (/home/bnewbold/dat/integration-tests/node_modules/tape/lib/test.js:373:10)
          at Test.bound [as error] (/home/bnewbold/dat/integration-tests/node_modules/tape/lib/test.js:77:32)
          at EventEmitter.<anonymous> (/home/bnewbold/dat/integration-tests/node_modules/tapenet/index.js:134:20)
          at emitOne (events.js:96:13)
          at EventEmitter.emit (events.js:191:7)
          at DestroyableTransform.<anonymous> (/home/bnewbold/dat/integration-tests/node_modules/mininet/index.js:294:10)
          at emitOne (events.js:96:13)
          at DestroyableTransform.emit (events.js:191:7)
  ...
```
(process hangs at that point)

Should I expect these to work on my system? Should I submit a PR setting up travis testing? I needed to `sudo apt install mininet` to get things to run at all.

**Comment by mafintosh** [comment]
Which version of node are you using?

**Comment by bnewbold** [comment]
```
bnewbold@orithena$ node --version
v7.10.1
```
(less than a year old)

**Comment by mafintosh** [comment]
@bnewbold linux mdns requires latest 8 or 9 cause of an api we need
